### ISSUE TITLE
How can this project be launched?

### ISSUE THREAD

**Issue by xkomiks** [zreecespieces/jamstack-ecommerce-course#2]
This project looks impressive, but I would like to know how can run it to get familiar with it.

Here are the problems I ran into:
In the back-end

1. I get this error and I can't figure out how to fix it.
```bash
Something went wrong installing the "sharp" module
Cannot find module '../build/Release/sharp.node'
```
2. It seems to me that after fixing the first error, it will not be possible to start because the database is not configured

@zreecespieces can you help with this?

**Comment by HelpMe-Pls** [comment]
@xkomiks I had that `sharp` error a few times then I tried to run `npm run clean` in the `frontend` folder, also delete the `node_modules` and `package-lock.json` then `npm i`. With the `backend` folder delete the `cache`, `build`, `exports` and `node_modules` then run `yarn`.  Then run `npm run develop` on the `backend` first and `frontend` follows. It works for me, try that out see if it helps.

**Comment by xkomiks** [comment]
@HelpMe-Pls thank you for your reply. I will soon try to run project according to your instructions.
